id = "org.knowlpedia.imported-content"
title = "Knowlpedia"
version = "0.1.0"
authors = ["Ryan Persson"]
license = "unknown-imported"
content_dir = "content"
development_content_dirs = ["testing"]

[outputs]
static_site = true
json_indexes = true
sqlite = true
